<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationTitle>Mux</ApplicationTitle>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.ico" />
  </ItemGroup>

</Project>
